In [60]:
import pandas as pd
import numpy as np
Data_Set=pd.read_excel("Bike_Sales_Functions_Lab.xlsx")
Data_Set.head(20)

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,2021-12-01,1,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,NaN,2295.0,4172,5008,9180
1,261696,2021-12-01,1,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1,1266.0,2320.0,1054,1266,2320
2,261697,2021-12-02,2,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2,420.0,769.0,698,840,1538
3,261695,2021-12-02,2,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1,420.0,769.0,349,420,769
4,261699,2021-12-03,3,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2,1252.0,2295.0,2086,2504,4590
5,261700,2021-12-03,3,December,2021,24,Youth (<25),F,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1,1252.0,2295.0,1043,1252,2295
6,261701,2021-12-03,3,December,2021,37,Adults (35-64),NaN,United States,Washington,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252.0,2295.0,1043,1252,2295
7,261702,2021-12-04,4,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",4,420.0,NaN,1396,1680,3076
8,261703,2021-12-05,5,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,1252.0,2295.0,4172,5008,9180
9,261704,2021-12-05,5,December,2021,42,Adults (35-64),M,Germany,Nordrhein-Westfalen,Bikes,Mountain Bikes,"Mountain-200 Black, 38",4,1252.0,2295.0,4172,5008,9180
10,261705,2021-12-05,5,December,2021,35,Adults (35-64),F,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1,1266.0,2320.0,1054,1266,2320
11,261701,2021-12-05,5,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252.0,2295.0,1043,1252,2295
12,261707,2021-12-06,6,December,2021,23,Youth (<25),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",3,420.0,NaN,1047,1260,2307
13,261708,2021-12-06,6,December,2021,27,Young Adults (25-34),M,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252.0,2295.0,1043,1252,2295
14,261709,2021-12-06,6,December,2021,36,Adults (35-64),M,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1,NaN,2295.0,1043,1252,2295
15,261710,2021-12-06,6,December,2021,47,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1,1266.0,2320.0,1054,1266,2320
16,261711,2021-12-07,7,December,2021,30,Young Adults (25-34),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 38",4,420.0,769.0,1396,1680,3076
17,261712,2021-12-07,7,December,2021,38,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",2,1266.0,2320.0,2108,2532,4640
18,261713,2021-12-08,8,December,2021,19,Youth (<25),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-500 Silver, 42",4,308.0,565.0,1028,1232,2260
19,261715,2021-12-08,8,December,2021,30,Young Adults (25-34),NaN,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",4,1266.0,2320.0,4216,5064,9280

In [61]:
duplicates=Data_Set.duplicated("Sales_Order #")
duplicates

0     False
1     False
2     False
3      True
4     False
      ...
83    False
84    False
85    False
86    False
87     True
Length: 88, dtype: bool

In [62]:
Total_duplicates=duplicates.sum()
Total_duplicates

np.int64(7)

In [63]:
# droping duplicates
Drop_Duplicates=Data_Set.drop_duplicates("Sales_Order #")
Drop_Duplicates.head(20)

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,2021-12-01,1,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,NaN,2295.0,4172,5008,9180
1,261696,2021-12-01,1,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1,1266.0,2320.0,1054,1266,2320
2,261697,2021-12-02,2,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2,420.0,769.0,698,840,1538
4,261699,2021-12-03,3,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2,1252.0,2295.0,2086,2504,4590
5,261700,2021-12-03,3,December,2021,24,Youth (<25),F,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1,1252.0,2295.0,1043,1252,2295
6,261701,2021-12-03,3,December,2021,37,Adults (35-64),NaN,United States,Washington,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252.0,2295.0,1043,1252,2295
7,261702,2021-12-04,4,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",4,420.0,NaN,1396,1680,3076
8,261703,2021-12-05,5,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,1252.0,2295.0,4172,5008,9180
9,261704,2021-12-05,5,December,2021,42,Adults (35-64),M,Germany,Nordrhein-Westfalen,Bikes,Mountain Bikes,"Mountain-200 Black, 38",4,1252.0,2295.0,4172,5008,9180
10,261705,2021-12-05,5,December,2021,35,Adults (35-64),F,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1,1266.0,2320.0,1054,1266,2320
12,261707,2021-12-06,6,December,2021,23,Youth (<25),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",3,420.0,NaN,1047,1260,2307
13,261708,2021-12-06,6,December,2021,27,Young Adults (25-34),M,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252.0,2295.0,1043,1252,2295
14,261709,2021-12-06,6,December,2021,36,Adults (35-64),M,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1,NaN,2295.0,1043,1252,2295
15,261710,2021-12-06,6,December,2021,47,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1,1266.0,2320.0,1054,1266,2320
16,261711,2021-12-07,7,December,2021,30,Young Adults (25-34),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 38",4,420.0,769.0,1396,1680,3076
17,261712,2021-12-07,7,December,2021,38,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",2,1266.0,2320.0,2108,2532,4640
18,261713,2021-12-08,8,December,2021,19,Youth (<25),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-500 Silver, 42",4,308.0,565.0,1028,1232,2260
19,261715,2021-12-08,8,December,2021,30,Young Adults (25-34),NaN,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",4,1266.0,2320.0,4216,5064,9280
21,261716,2021-12-08,8,December,2021,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",1,295.0,540.0,245,295,540
22,261717,2021-12-09,9,December,2021,33,Young Adults (25-34),F,Australia,Victoria,Bikes,Mountain Bikes,"Mountain-100 Black, 38",2,1898.0,3375.0,2954,3796,6750

In [64]:
# finding null values in the data set
Null_values=Data_Set.isnull()

In [65]:
# Total null values in data_set
Total_null_values=Null_values.sum()
Total_null_values

Sales_Order #          0
Date                   0
Day                    0
Month                  0
Year                   0
Customer_Age           0
Age_Group              0
Customer_Gender        2
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    0
Order_Quantity         0
Unit_Cost              3
Unit_Price             2
Profit                 0
Cost                   0
Revenue                0
dtype: int64

In [66]:
#  handling customer gender column nan values using bfill method
Data_Set["Customer_Gender"]=Data_Set["Customer_Gender"].fillna(method="bfill")
Data_Set.head(20)

C:\Users\Muhammad Asad khan\AppData\Local\Temp\ipykernel_1368\1270118855.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Data_Set["Customer_Gender"]=Data_Set["Customer_Gender"].fillna(method="bfill")

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,2021-12-01,1,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,NaN,2295.0,4172,5008,9180
1,261696,2021-12-01,1,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1,1266.0,2320.0,1054,1266,2320
2,261697,2021-12-02,2,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2,420.0,769.0,698,840,1538
3,261695,2021-12-02,2,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1,420.0,769.0,349,420,769
4,261699,2021-12-03,3,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2,1252.0,2295.0,2086,2504,4590
5,261700,2021-12-03,3,December,2021,24,Youth (<25),F,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1,1252.0,2295.0,1043,1252,2295
6,261701,2021-12-03,3,December,2021,37,Adults (35-64),F,United States,Washington,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252.0,2295.0,1043,1252,2295
7,261702,2021-12-04,4,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",4,420.0,NaN,1396,1680,3076
8,261703,2021-12-05,5,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,1252.0,2295.0,4172,5008,9180
9,261704,2021-12-05,5,December,2021,42,Adults (35-64),M,Germany,Nordrhein-Westfalen,Bikes,Mountain Bikes,"Mountain-200 Black, 38",4,1252.0,2295.0,4172,5008,9180
10,261705,2021-12-05,5,December,2021,35,Adults (35-64),F,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1,1266.0,2320.0,1054,1266,2320
11,261701,2021-12-05,5,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252.0,2295.0,1043,1252,2295
12,261707,2021-12-06,6,December,2021,23,Youth (<25),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",3,420.0,NaN,1047,1260,2307
13,261708,2021-12-06,6,December,2021,27,Young Adults (25-34),M,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252.0,2295.0,1043,1252,2295
14,261709,2021-12-06,6,December,2021,36,Adults (35-64),M,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1,NaN,2295.0,1043,1252,2295
15,261710,2021-12-06,6,December,2021,47,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1,1266.0,2320.0,1054,1266,2320
16,261711,2021-12-07,7,December,2021,30,Young Adults (25-34),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 38",4,420.0,769.0,1396,1680,3076
17,261712,2021-12-07,7,December,2021,38,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",2,1266.0,2320.0,2108,2532,4640
18,261713,2021-12-08,8,December,2021,19,Youth (<25),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-500 Silver, 42",4,308.0,565.0,1028,1232,2260
19,261715,2021-12-08,8,December,2021,30,Young Adults (25-34),F,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",4,1266.0,2320.0,4216,5064,9280

In [67]:

print(Data_Set.columns.str.strip())

Index(['Sales_Order #', 'Date', 'Day', 'Month', 'Year', 'Customer_Age',
       'Age_Group', 'Customer_Gender', 'Country', 'State', 'Product_Category',
       'Sub_Category', 'Product_Description', 'Order_Quantity', 'Unit_Cost',
       'Unit_Price', 'Profit', 'Cost', 'Revenue'],
      dtype='object')

In [71]:
Data_Set.head()

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,2021-12-01,1,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,NaN,2295.0,4172,5008,9180
1,261696,2021-12-01,1,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1,1266.0,2320.0,1054,1266,2320
2,261697,2021-12-02,2,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2,420.0,769.0,698,840,1538
3,261695,2021-12-02,2,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1,420.0,769.0,349,420,769
4,261699,2021-12-03,3,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2,1252.0,2295.0,2086,2504,4590

In [80]:
print(list(Data_Set.columns))
Data_Set.rename(columns={"Unit_Cost ":"Unit_Cost","Unit_Price ":"Unit_Price",'Cost ':"Cost"},inplace=True)
Data_Set.head().columns

['Sales_Order #', 'Date', 'Day', 'Month', 'Year', 'Customer_Age', 'Age_Group', 'Customer_Gender', 'Country', 'State', 'Product_Category', 'Sub_Category', 'Product_Description', 'Order_Quantity', 'Unit_Cost', 'Unit_Price', 'Profit ', 'Cost', 'Revenue']

Index(['Sales_Order #', 'Date', 'Day', 'Month', 'Year', 'Customer_Age',
       'Age_Group', 'Customer_Gender', 'Country', 'State', 'Product_Category',
       'Sub_Category', 'Product_Description', 'Order_Quantity', 'Unit_Cost',
       'Unit_Price', 'Profit ', 'Cost', 'Revenue'],
      dtype='object')

In [83]:
# Replacing null value with mean of Unit_cost, Unit_price and Cost
print("Mean of Unit Cost:",Data_Set["Unit_Cost"].mean())
print("Mean of Unit Price:",Data_Set["Unit_Price"].mean())

Mean of Unit Cost: 1067.3647058823528
Mean of Unit Price: 1973.0232558139535

In [85]:
# replacing null with means
Data_Set["Unit_Cost"]=Data_Set["Unit_Cost"].replace(np.nan,1067)
Data_Set["Unit_Price"]=Data_Set["Unit_Price"].replace(np.nan,1973)

In [86]:
Data_Set

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,2021-12-01,1,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,1067.0,2295.0,4172,5008,9180
1,261696,2021-12-01,1,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1,1266.0,2320.0,1054,1266,2320
2,261697,2021-12-02,2,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2,420.0,769.0,698,840,1538
3,261695,2021-12-02,2,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1,420.0,769.0,349,420,769
4,261699,2021-12-03,3,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2,1252.0,2295.0,2086,2504,4590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,261778,2021-12-22,22,December,2021,41,Adults (35-64),M,Germany,Hessen,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1,1266.0,2320.0,1054,1266,2320
84,261779,2021-12-23,23,December,2021,30,Young Adults (25-34),F,United States,Oregon,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1,1266.0,2320.0,1054,1266,2320
85,261780,2021-12-23,23,December,2021,31,Young Adults (25-34),F,Canada,British Columbia,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1,1252.0,2295.0,1043,1252,2295
86,261781,2021-12-23,23,December,2021,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",1,295.0,540.0,245,295,540
87,261780,2021-12-24,24,December,2021,38,Adults (35-64),M,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Black, 42",4,1252.0,2295.0,4172,5008,9180